"""Add enterprise data quality rules

Revision ID: 084bc8b5e18b
Revises: 35b5d0835265
Create Date: 2025-09-26 11:57:04.850264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084bc8b5e18b'
down_revision = '35b5d0835265'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_compliance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('compliance_framework', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('compliance_framework', sa.String(length=100), nullable=True),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('data_classification', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='rulestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_rule_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['data_quality_rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', 'INFO', name='ruleseverity'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='rulestatus'), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('parent_rule_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_tags', sa.JSON(), nullable=True),
    sa.Column('business_owner', sa.String(length=255), nullable=True),
    sa.Column('technical_owner', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['data_quality_rules.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_rule_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'ACTIVATE', 'DEPRECATE', 'ARCHIVE', name='auditaction'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['data_quality_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_quality_rule_audit')
    op.drop_table('data_quality_rules')
    op.drop_table('data_quality_rule_assignments')
    op.drop_table('data_quality_rule_sets')
    op.drop_table('data_quality_compliance_reports')
    # ### end Alembic commands ###
