"""add_pipeline_runs

Revision ID: 56c47c1bfe30
Revises: 2507e4fa6f84
Create Date: 2025-09-20 17:51:43.751262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c47c1bfe30'
down_revision = '2507e4fa6f84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='pipelinerunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dag_run_id', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_runs_dag_run_id', 'pipeline_runs', ['dag_run_id'], unique=False)
    op.create_index('idx_pipeline_runs_product_version', 'pipeline_runs', ['product_id', 'version'], unique=False)
    op.create_index('idx_pipeline_runs_workspace_id', 'pipeline_runs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_dag_run_id'), 'pipeline_runs', ['dag_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_product_id'), 'pipeline_runs', ['product_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_workspace_id'), 'pipeline_runs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_workspace_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_product_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_dag_run_id'), table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_workspace_id', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_product_version', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_dag_run_id', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
