"""add_chunking_and_embedding_config_to_products

Revision ID: a3ee91772c51
Revises: 56c47c1bfe30
Create Date: 2025-09-24 12:36:56.673504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ee91772c51'
down_revision = '56c47c1bfe30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('chunking_config', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('embedding_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embedding_config')
    op.drop_column('products', 'chunking_config')
    # ### end Alembic commands ###
