"""remove_document_and_vector_metadata_tables

Revision ID: bda98fc65abe
Revises: a8b9c0d1e2f3
Create Date: 2025-12-27 16:17:52.789995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bda98fc65abe'
down_revision = 'a8b9c0d1e2f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vector_metadata_chunk_id', table_name='vector_metadata')
    op.drop_index('idx_vector_metadata_collection', table_name='vector_metadata')
    op.drop_index('idx_vector_metadata_field_name', table_name='vector_metadata')
    op.drop_index('idx_vector_metadata_product_version', table_name='vector_metadata')
    op.drop_index('ix_vector_metadata_chunk_id', table_name='vector_metadata')
    op.drop_index('ix_vector_metadata_field_name', table_name='vector_metadata')
    op.drop_index('ix_vector_metadata_id', table_name='vector_metadata')
    op.drop_index('ix_vector_metadata_product_id', table_name='vector_metadata')
    op.drop_table('vector_metadata')
    op.drop_index('idx_document_metadata_chunk_id', table_name='document_metadata')
    op.drop_index('idx_document_metadata_field_name', table_name='document_metadata')
    op.drop_index('idx_document_metadata_product_version', table_name='document_metadata')
    op.drop_index('ix_document_metadata_chunk_id', table_name='document_metadata')
    op.drop_index('ix_document_metadata_id', table_name='document_metadata')
    op.drop_index('ix_document_metadata_product_id', table_name='document_metadata')
    op.drop_table('document_metadata')
    op.create_index(op.f('ix_custom_playbooks_owner_user_id'), 'custom_playbooks', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_custom_playbooks_workspace_id'), 'custom_playbooks', ['workspace_id'], unique=False)
    op.drop_column('products', 'aird_embedding_index_path')
    op.drop_column('products', 'aird_trust_score')
    op.drop_column('products', 'aird_playbook_id')
    op.drop_column('products', 'aird_optimizer_notes')
    op.drop_column('products', 'aird_chunks_indexed')
    op.drop_column('products', 'aird_policy')
    op.drop_column('products', 'aird_last_run_at')
    op.drop_column('products', 'aird_fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('aird_fingerprint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_chunks_indexed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_optimizer_notes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_playbook_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_trust_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_embedding_index_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_custom_playbooks_workspace_id'), table_name='custom_playbooks')
    op.drop_index(op.f('ix_custom_playbooks_owner_user_id'), table_name='custom_playbooks')
    op.create_table('document_metadata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extra_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='document_metadata_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_metadata_pkey')
    )
    op.create_index('ix_document_metadata_product_id', 'document_metadata', ['product_id'], unique=False)
    op.create_index('ix_document_metadata_id', 'document_metadata', ['id'], unique=False)
    op.create_index('ix_document_metadata_chunk_id', 'document_metadata', ['chunk_id'], unique=False)
    op.create_index('idx_document_metadata_product_version', 'document_metadata', ['product_id', 'version'], unique=False)
    op.create_index('idx_document_metadata_field_name', 'document_metadata', ['field_name'], unique=False)
    op.create_index('idx_document_metadata_chunk_id', 'document_metadata', ['chunk_id'], unique=False)
    op.create_table('vector_metadata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='vector_metadata_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vector_metadata_pkey')
    )
    op.create_index('ix_vector_metadata_product_id', 'vector_metadata', ['product_id'], unique=False)
    op.create_index('ix_vector_metadata_id', 'vector_metadata', ['id'], unique=False)
    op.create_index('ix_vector_metadata_field_name', 'vector_metadata', ['field_name'], unique=False)
    op.create_index('ix_vector_metadata_chunk_id', 'vector_metadata', ['chunk_id'], unique=False)
    op.create_index('idx_vector_metadata_product_version', 'vector_metadata', ['product_id', 'version'], unique=False)
    op.create_index('idx_vector_metadata_field_name', 'vector_metadata', ['field_name'], unique=False)
    op.create_index('idx_vector_metadata_collection', 'vector_metadata', ['collection_id'], unique=False)
    op.create_index('idx_vector_metadata_chunk_id', 'vector_metadata', ['chunk_id'], unique=False)
    # ### end Alembic commands ###
