"""check_model_sync

Revision ID: cda8127f12b1
Revises: e6e0ecfee19f
Create Date: 2026-01-19 19:38:36.266843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda8127f12b1'
down_revision = 'e6e0ecfee19f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_eval_runs_id'), 'eval_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_runs_id'), table_name='eval_runs')
    # ### end Alembic commands ###
